"""add moderator note to event

Revision ID: 286e2975cf7b
Revises: 29883eea1315
Create Date: 2026-08-20 02:34:14.402591
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '286e2975cf7b'
down_revision: Union[str, Sequence[str], None] = '29883eea1315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('moderator_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'moderator_note')
    # ### end Alembic commands ###
