"""add ingest pipeline tables

Revision ID: 88ffab42ec5f
Revises: 286e2975cf7b
Create Date: 2026-08-24 00:00:00.000000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '88ffab42ec5f'
down_revision: Union[str, Sequence[str], None] = '286e2975cf7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('image_url', sa.Text(), nullable=True))
    op.create_table('ingested_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.Text(), nullable=False),
    sa.Column('item_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('received', 'projected', 'skipped', name='ingested_item_status'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingested_items_item_id'), 'ingested_items', ['item_id'], unique=True)
    op.create_table('event_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_sources')
    op.drop_index(op.f('ix_ingested_items_item_id'), table_name='ingested_items')
    op.drop_table('ingested_items')
    op.drop_column('event', 'image_url')
    # ### end Alembic commands ###
