"""add indexes on event status and start_at

Revision ID: b1e7d3f2c591
Revises: e7c08ee057e9
Create Date: 2026-08-27 01:25:38.207100
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1e7d3f2c591'
down_revision: Union[str, Sequence[str], None] = 'e7c08ee057e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_event_start_at'), 'event', ['start_at'], unique=False)
    op.create_index(op.f('ix_event_status'), 'event', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_status'), table_name='event')
    op.drop_index(op.f('ix_event_start_at'), table_name='event')
    # ### end Alembic commands ###
