"""add notifications table and user min_priority

Revision ID: e7c08ee057e9
Revises: 88ffab42ec5f
Create Date: 2026-08-27 00:52:37.126743
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM as PGEnum


# revision identifiers, used by Alembic.
revision: str = 'e7c08ee057e9'
down_revision: Union[str, Sequence[str], None] = '88ffab42ec5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


notification_priority_type = PGEnum(
    'critical', 'high', 'medium', 'low', name='notification_priority'
)
# Referenced by two columns below; create_type=False stops each column DDL from
# re-issuing CREATE TYPE for a type already created explicitly further down.
notification_priority = PGEnum(
    'critical', 'high', 'medium', 'low', name='notification_priority', create_type=False
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    notification_priority_type.create(op.get_bind(), checkfirst=True)
    op.create_table('notification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('priority', notification_priority, nullable=False),
    sa.Column('channel', sa.Enum('in_app', name='notification_channel'), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('min_priority', notification_priority, server_default='low', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'min_priority')
    op.drop_table('notification')
    notification_priority_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
